@startuml python-ci-summary

start 

if (workflow_dispatch ?) then (yes)
elseif (push to main branch ?) then (yes)
elseif (pull_request ?) then (yes)
elseif (scheduled by cron ?) then (yes)
else (no)
  stop
endif

fork
  :build;
fork again
  :dockerize;
  partition "Container Scan" {
    fork
      :trivy;
    fork again
      :anchore-image;
    end fork
  }

fork again
  :anchore-files;
fork again
  :hadolint;
end fork
stop

@enduml
